name: "Build, Test, Lint rpminfo"
on:
  push:
    branches:
      - main

jobs:
  golang_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: '1.14'

      - name: Super Linter
        uses: docker://github/super-linter:v2.2.0

      - name: Run Tests
        run: make test
      - name: Lint
        run: make lint
      - name: Build
        run: make build
