name: "Build, Test, Lint rpminfo"
on:
  push:
    branches:
      - main

jobs:
  golang_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Super Linter
        uses: docker://github/super-linter:v2.2.0
        # TODO: Remove once errors are fixed
        # ref: https://github.com/frezbo/rpminfo/runs/816329853?check_suite_focus=true
        env:
          VALIDATE_GO: false

      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: '1.14'

      - name: Run Tests
        run: make test
      - name: Lint
        run: make lint
      - name: Build
        run: make build
